version: '3.8'
services:
    server:
        build: .
        ports:
            - '8080:3000'
        env_file:
            - .env.docker
        links:
            - database
        command: ['node', './build/app.js']

    database:
        image: postgres
        environment:
            - POSTGRES_DB=agileMonkeyDb
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=cartero
        ports:
            - 5432:5432
        volumes:
            - database-data:/var/lib/postgres/data

volumes:
    database-data: {}
